import React, { useState } from 'react';
import Head from 'next/head';
import { motion } from 'framer-motion';
import WalletForm from '../components/WalletForm';
import Dashboard from '../components/Dashboard';
import { getWalletBalances } from './api/wallet';
import type { Balance } from './api/wallet';

export default function Home() {
  const [assets, setAssets] = useState<Balance[]>([]);
  
  const handleFormSubmit = async (address: string) => {
    const fetchedAssets = await getWalletBalances(address);
    setAssets(fetchedAssets);
  };

  return (
    <>
      <Head>
        <title>Pulsar Portfolio</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
          className='container mx-auto px-4'
        >
          <WalletForm onSubmitAddress={handleFormSubmit} />
          { assets.length > 0 && <Dashboard assets={assets} />}
        </motion.div>
      </main>
    </>
  );
}
